[tool.poetry]
name = "SciDataLib"
version = "0.2.5"
description = "Python library for development of SciData JSON-LD files"
authors = [
    "Stuart Chalk <schalk@unf.edu>",
    "Dylan Johnson <n01448636@unf.edu>",
    "Marshall McDonnell <mcdonnellmt@ornl.gov>"
]
license = "MIT"
readme = "README.md"
homepage = "https://github.com/ChalkLab/SciDataLib"
repository = "https://github.com/ChalkLab/SciDataLib"
keywords = ["scidata", "scidatalib"]
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent"
]

[tool.poetry.scripts]
scidatalib = "scidatalib.cli:cli"

[tool.poetry.dependencies]
python = "^3.7"
pytest-cov = "^2.11.1"
numpy = "^1.20.2"

[tool.poetry.dev-dependencies]
pytest = "^5.2"
flake8 = "^3.8.4"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
